# NTK classifier for Cora

In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import torch
import numpy as np
from exp_ntk_certify_single import run

In [3]:
def get_str_l(l, precision=2):
    l_str = []
    for el in l:
        l_str.append(f"{el:.{precision}f}")
    return l_str
    

In [7]:
seed = 0

data_params = dict(
    dataset = "cora",
    learning_setting = "inductive", # or "transdructive"
    specification = dict(
        n_per_class = 20,
        fraction_test = 0.1,
        data_dir = "./data",
        make_undirected = True,
        binary_attr = False,
        balance_test = True,
    )
)

model_params = dict(
    label = "GCN",
    model = "GCN",
    normalization = "row_normalization",
    depth = 1,
    #regularizer = 1e-8
    regularizer = 1,
    pred_method = "svm",
)

certificate_params = dict(
    perturbation_model = "l0",
    delta = 5 # l0: local budget = delta * feature_dim
)

verbosity_params = dict(
    debug_lvl = "warning"
)  

other_params = dict(
    device = "0",
    dtype = torch.float64,
    allow_tf32 = False
)

In [8]:
def run_exp(n_seeds, data_params, model_params, certificate_params,
            verbosity_params, other_params):
    acc_l = []
    min_ypred = []
    max_ypred = []
    cond = []
    min_ntklabeled = []
    max_ntklabeled = []
    min_ntkunlabeled = []
    max_ntkunlabeled = []
    for seed in range(n_seeds):
        data_params["specification"]["seed"] = seed
        res = run(data_params, model_params, certificate_params,
                  verbosity_params, other_params, seed)
        acc_l.append(res["accuracy"])
        min_ypred.append(res["min_ypred"])
        max_ypred.append(res["max_ypred"])
        min_ntklabeled.append(res["min_ntklabeled"])
        max_ntklabeled.append(res["max_ntklabeled"])
        min_ntkunlabeled.append(res["min_ntkunlabeled"])
        max_ntkunlabeled.append(res["max_ntkunlabeled"])
        cond.append(res["cond"])
    print(f"Accuracy: {get_str_l(acc_l)}")
    print(f"Min y_pred: {get_str_l(min_ypred)}")
    print(f"Max y_pred: {get_str_l(max_ypred)}")
    print(f"Min NTK_labeled: {get_str_l(min_ntklabeled)}")
    print(f"Max NTK_labeled: {get_str_l(max_ntklabeled)}")
    print(f"Min NTK_unlabeled: {get_str_l(min_ntkunlabeled)}")
    print(f"Max NTK_unlabeled: {get_str_l(max_ntkunlabeled)}")
    print(f"Condition: {get_str_l(cond, precision=0)}")

In [15]:
model_params["regularizer"] = 0.1
model_params["pred_method"] = "svm"
model_params["cache_size"] = 10000
data_params["dataset"] = "cora"
other_params["device"] = 0
certificate_params["delta"] = 5
verbosity_params["debug_lvl"] = "info"
seed = 0
data_params["specification"]["seed"] = seed
run(data_params, model_params, certificate_params, verbosity_params, other_params, seed)

2024-01-15 17:27:28 (INFO): Starting experiment exp_ntk_certify_single with configuration:
2024-01-15 17:27:28 (INFO): data_params: {'dataset': 'cora', 'learning_setting': 'inductive', 'specification': {'n_per_class': 20, 'fraction_test': 0.1, 'data_dir': './data', 'make_undirected': True, 'binary_attr': False, 'balance_test': True, 'seed': 0}}
2024-01-15 17:27:28 (INFO): model_params: {'label': 'GCN', 'model': 'GCN', 'normalization': 'row_normalization', 'depth': 1, 'regularizer': 0.1, 'pred_method': 'svm', 'cache_size': 10000}
2024-01-15 17:27:28 (INFO): certification_params: {'perturbation_model': 'l0', 'delta': 5}
2024-01-15 17:27:28 (INFO): verbosity_params: {'debug_lvl': 'info'}
2024-01-15 17:27:28 (INFO): other_params: {'device': 0, 'dtype': torch.float64, 'allow_tf32': False}
2024-01-15 17:27:28 (INFO): seed: 0
2024-01-15 17:27:28 (INFO): Currently on gpu device cuda:0
2024-01-15 17:27:28 (INFO): X.min(): 0.0
2024-01-15 17:27:28 (INFO): X.max(): 1.0
2024-01-15 17:27:28 (INFO): 

Calc 0
0.0
0.0
Calc 10
0.5454545454545454
0.0
Calc 20
0.6190476190476191
0.09523809523809523
Calc 30
0.5806451612903226
0.06451612903225806


KeyboardInterrupt: 

In [29]:
model_params["regularizer"] = 0.1
model_params["pred_method"] = "svm"
model_params["cache_size"] = 10000
data_params["dataset"] = "cora"
other_params["device"] = 0
certificate_params["delta"] = 1
verbosity_params["debug_lvl"] = "info"
seed = 0
data_params["specification"]["seed"] = seed
run(data_params, model_params, certificate_params, verbosity_params, other_params, seed)

2024-01-15 18:14:21 (INFO): Starting experiment exp_ntk_certify_single with configuration:
2024-01-15 18:14:21 (INFO): data_params: {'dataset': 'cora', 'learning_setting': 'inductive', 'specification': {'n_per_class': 20, 'fraction_test': 0.1, 'data_dir': './data', 'make_undirected': True, 'binary_attr': False, 'balance_test': True, 'seed': 0}}
2024-01-15 18:14:21 (INFO): model_params: {'label': 'GCN', 'model': 'GCN', 'normalization': 'row_normalization', 'depth': 1, 'regularizer': 0.1, 'pred_method': 'svm', 'cache_size': 10000}
2024-01-15 18:14:21 (INFO): certification_params: {'perturbation_model': 'l0', 'delta': 1}
2024-01-15 18:14:21 (INFO): verbosity_params: {'debug_lvl': 'info'}
2024-01-15 18:14:21 (INFO): other_params: {'device': 0, 'dtype': torch.float64, 'allow_tf32': False}
2024-01-15 18:14:21 (INFO): seed: 0
2024-01-15 18:14:21 (INFO): Currently on gpu device cuda:0
2024-01-15 18:14:21 (INFO): X.min(): 0.0
2024-01-15 18:14:21 (INFO): X.max(): 1.0
2024-01-15 18:14:21 (INFO): 

Calc 0
tensor([[-0.4467, -1.0587, -0.5451, -1.2761, -0.7634, -0.8060, -1.0860]],
       device='cuda:0')
tensor([[2.7941, 1.8528, 1.4351, 1.4662, 1.8322, 1.5657, 1.5958]],
       device='cuda:0')
tensor([[-3.6729, -4.0233, -2.5276, -3.9893, -3.3300, -3.2051, -3.7690]],
       device='cuda:0')
0.0
0.0
Calc 10
tensor([[-1.1027, -0.9729, -0.9998, -0.4061, -0.3088, -0.8725, -1.0280]],
       device='cuda:0')
tensor([[3.1608, 3.0013, 1.7194, 3.8339, 3.4738, 2.2193, 2.2959]],
       device='cuda:0')
tensor([[-5.2330, -4.9161, -3.7273, -4.9086, -4.1376, -3.9032, -4.2641]],
       device='cuda:0')
0.0
0.0
Calc 20
tensor([[-0.2904, -0.8960, -1.1215, -0.8002, -1.0015, -1.0357, -1.0470]],
       device='cuda:0')
tensor([[2.7973, 1.8408, 0.5404, 1.7634, 1.2743, 1.1199, 1.3981]],
       device='cuda:0')
tensor([[-3.3964, -3.6678, -2.6962, -3.3393, -3.2857, -3.1640, -3.5355]],
       device='cuda:0')
0.0
0.0
Calc 30
tensor([[-0.7861, -0.5934, -0.2777, -1.4867, -0.7408, -0.5735, -1.1407]],
       dev

KeyboardInterrupt: 

In [8]:
y_pred = torch.tensor(([1, 2, 3], [1, 3, 2], [3, 2, 1]))
y_lb = torch.tensor(([0, 1, 2], [0, 2, 1], [2, 1, 0]))
y_ub = torch.tensor(([3, 3, 4], [1, 3, 1.5], [3, 4, 1]))
n = y_pred.shape[0]
pred_orig = y_pred.argmax(1)
print(pred_orig)
pred_orig_lb = y_lb[range(n), pred_orig]
print(pred_orig_lb)
mask = torch.ones(y_ub.shape, dtype=torch.bool).to(y_ub.device)
mask[range(n), pred_orig] = False
pred_other_ub = y_ub[mask].reshape((n, y_ub.shape[1]-1))
print(pred_other_ub)
count_beaten = (pred_other_ub > pred_orig_lb.reshape(-1, 1)).sum(dim=1)
print(count_beaten)
print(((count_beaten == 0).sum() / n).cpu().item())


tensor([2, 1, 0])
tensor([2, 2, 2])
tensor([[3.0000, 3.0000],
        [1.0000, 1.5000],
        [4.0000, 1.0000]])
tensor([2, 0, 1])
0.3333333432674408


# SVM

In [ ]:
model_params["regularizer"] = 0.1
data_params["dataset"] = "cora"
model_params["pred_method"] = "svm"
n_seeds = 10
run_exp(n_seeds, data_params, model_params, verbosity_params, other_params)

In [ ]:
model_params["regularizer"] = 0.1
data_params["dataset"] = "cora"
model_params["pred_method"] = "svm"
n_seeds = 10
run_exp(n_seeds, data_params, model_params, verbosity_params, other_params)

In [ ]:
model_params["regularizer"] = 1
data_params["dataset"] = "cora"
model_params["pred_method"] = "krr"
n_seeds = 2
run_exp(n_seeds, data_params, model_params, verbosity_params, other_params)