In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import torch
import numpy as np
from exp_ntk_certify import run

In [3]:
seed = 0

data_params = dict(
    dataset = "csbm",
    learning_setting = "transductive", # or "transdructive"
    specification = dict(
        classes = 2,
        n_trn_labeled = 10,
        n_trn_unlabeled = 0,
        n_val = 10,
        n_test = 20,
        sigma = 1,
        avg_within_class_degree = 1.58 * 2,
        avg_between_class_degree = 0.37 * 2,
        K = 1.5,
        seed = 0 # used to generate the dataset & data split
    )
)

model_params = dict(
    label = "GCN",
    model = "GCN",
    normalization = "row_normalization",
    depth = 1,
    #regularizer = 1e-8
    regularizer = 1,
    pred_method = "svm",
)

certificate_params = dict(
    n_adversarial = 1, # number adversarial nodes
    perturbation_model = "linf",
    delta = 0.01 # l0: local budget = delta * feature_dim
)

verbosity_params = dict(
    debug_lvl = "warning"
)  

other_params = dict(
    device = "0",
    dtype = torch.float64,
    allow_tf32 = False
)

In [80]:
model_params["cache_size"] = 10000
data_params["specification"]["avg_within_class_degree"] = 1.58 * 2
data_params["specification"]["avg_between_class_degree"] = 0.37 * 2
other_params["device"] = 0
other_params["debug"] = True
certificate_params["n_adversarial"] = 20
certificate_params["delta"] = 0.1
certificate_params["method"] = "XXT"
certificate_params["perturbation_model"] = "linf"
certificate_params["cert_method"] = "bilevel_svm"
verbosity_params["debug_lvl"] = "info"
model_params["regularizer"] = 0.005
model_params["solver"] = "cvxopt"
model_params["alpha_tol"] = 1e-4
model_params["bias"] = False
data_params["learning_setting"] = "transductive"
run(data_params, model_params, certificate_params, verbosity_params, other_params, seed)

2024-04-04 20:55:23 (INFO): Starting experiment exp_ntk_certify with configuration:
2024-04-04 20:55:23 (INFO): data_params: {'dataset': 'csbm', 'learning_setting': 'transductive', 'specification': {'classes': 2, 'n_trn_labeled': 10, 'n_trn_unlabeled': 0, 'n_val': 10, 'n_test': 20, 'sigma': 1, 'avg_within_class_degree': 3.16, 'avg_between_class_degree': 0.74, 'K': 1.5, 'seed': 0}}
2024-04-04 20:55:23 (INFO): model_params: {'label': 'GCN', 'model': 'GCN', 'normalization': 'row_normalization', 'depth': 1, 'regularizer': 0.005, 'pred_method': 'svm', 'cache_size': 10000, 'solver': 'cvxopt', 'alpha_tol': 0.0001, 'bias': False}
2024-04-04 20:55:23 (INFO): certification_params: {'n_adversarial': 20, 'perturbation_model': 'linf', 'delta': 0.1, 'method': 'XXT', 'cert_method': 'bilevel_svm'}
2024-04-04 20:55:23 (INFO): verbosity_params: {'debug_lvl': 'info'}
2024-04-04 20:55:23 (INFO): other_params: {'device': 0, 'dtype': torch.float64, 'allow_tf32': False, 'debug': True}
2024-04-04 20:55:23 (IN

CSBM mu:
[0.4330127 0.4330127 0.4330127]
X.mean() 0.17639265186771808
Sig.mean(): 0.36988448929507456
Sig.min(): -1.6167828163040219
Sig.max(): 4.644553232768731
Depth 0
E_der.min(): 0.05886886208169891
E_der.max(): 1.0
Sig.mean(): 0.5356731910240182
Sig.min(): 0.032657908105640024
Sig.max(): 2.149047264537059
tensor([[ 1.3716,  0.2269,  0.3171,  ...,  0.6583,  0.1156, -0.0652],
        [ 0.2269,  0.5839,  0.2018,  ...,  0.7162,  0.8862,  0.5957],
        [ 0.3171,  0.2018,  0.2248,  ...,  0.3432,  0.4679,  0.2430],
        ...,
        [ 0.6583,  0.7162,  0.3432,  ...,  1.9889,  1.5540,  0.5962],
        [ 0.1156,  0.8862,  0.4679,  ...,  1.5540,  2.2469,  1.2198],
        [-0.0652,  0.5957,  0.2430,  ...,  0.5962,  1.2198,  1.0697]],
       device='cuda:0', dtype=torch.float64)
     pcost       dcost       gap    pres   dres
 0: -8.4542e+00 -4.4154e-01  9e+01  1e+01  4e-16
 1: -6.4585e-01 -2.4779e-01  5e+00  5e-01  6e-16
 2: -7.8310e-02 -2.0507e-01  1e-01  5e-17  5e-16
 3: -9.1857e-0

AssertionError: 

In [28]:
model_params["cache_size"] = 10000
data_params["specification"]["avg_within_class_degree"] = 1.58 * 2
data_params["specification"]["avg_between_class_degree"] = 0.37 * 2
other_params["device"] = 0
certificate_params["n_adversarial"] = 20
certificate_params["delta"] = 0.1
certificate_params["method"] = "XXT"
certificate_params["perturbation_model"] = "linf"
certificate_params["cert_method"] = "bilevel_svm"
verbosity_params["debug_lvl"] = "info"
model_params["regularizer"] = 0.005
model_params["solver"] = "cvxopt"
model_params["alpha_tol"] = 1e-4
model_params["bias"] = False
data_params["learning_setting"] = "transductive"
run(data_params, model_params, certificate_params, verbosity_params, other_params, seed)

2024-04-04 17:46:11 (INFO): Starting experiment exp_ntk_certify with configuration:
2024-04-04 17:46:11 (INFO): data_params: {'dataset': 'csbm', 'learning_setting': 'transductive', 'specification': {'classes': 2, 'n_trn_labeled': 10, 'n_trn_unlabeled': 0, 'n_val': 10, 'n_test': 20, 'sigma': 1, 'avg_within_class_degree': 3.16, 'avg_between_class_degree': 0.74, 'K': 1.5, 'seed': 0}}
2024-04-04 17:46:11 (INFO): model_params: {'label': 'GCN', 'model': 'GCN', 'normalization': 'row_normalization', 'depth': 1, 'regularizer': 0.005, 'pred_method': 'svm', 'cache_size': 10000, 'solver': 'cvxopt', 'alpha_tol': 0.0001, 'bias': False}
2024-04-04 17:46:11 (INFO): certification_params: {'n_adversarial': 20, 'perturbation_model': 'linf', 'delta': 0.1, 'method': 'XXT', 'cert_method': 'bilevel_svm'}
2024-04-04 17:46:11 (INFO): verbosity_params: {'debug_lvl': 'info'}
2024-04-04 17:46:11 (INFO): other_params: {'device': 0, 'dtype': torch.float64, 'allow_tf32': False}
2024-04-04 17:46:11 (INFO): seed: 0
20

CSBM mu:
[0.4330127 0.4330127 0.4330127]
X.mean() 0.17639265186771808
Depth 0
nan: 0
u_lb: tensor([[ 0.7972, -1.0000,  0.8160,  ...,  0.2879, -1.0000, -1.0000],
        [-1.0000,  0.0000, -1.0000,  ..., -1.0000, -1.0000,  0.0879],
        [ 0.8160, -1.0000,  1.0000,  ...,  0.1721, -1.0000, -1.0000],
        ...,
        [ 0.2879, -1.0000,  0.1721,  ...,  0.8157,  0.2240, -0.3499],
        [-1.0000, -1.0000, -1.0000,  ...,  0.2240,  0.2001,  0.1653],
        [-1.0000,  0.0879, -1.0000,  ..., -0.3499,  0.1653,  0.7357]],
       device='cuda:0', dtype=torch.float64)


AssertionError: 