In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import os
os.environ["GRB_LICENSE_FILE"] = "/ceph/ssd/staff/gosl/app/gurobi.lic"


In [3]:
import torch
import numpy as np
from exp_ntk_certify import run

In [18]:
seed = 0

data_params = dict(
    dataset = "csbm",
    learning_setting = "transductive", # or "transdructive"
    specification = dict(
        classes = 2,
        n_trn_labeled = 40,
        n_trn_unlabeled = 0,
        n_val = 40,
        n_test = 200,
        sigma = 1,
        avg_within_class_degree = 1.58 * 2,
        avg_between_class_degree = 0.37 * 2,
        K = 1.5,
        seed = 0 # used to generate the dataset & data split
    )
)

model_params = dict(
    label = "GCN",
    model = "GCN",
    normalization = "row_normalization",
    depth = 1,
    #regularizer = 1e-8
    regularizer = 1,
    pred_method = "svm",
)

certificate_params = dict(
    n_adversarial = 1, # number adversarial nodes
    perturbation_model = "linf",
    delta = 0.01 # l0: local budget = delta * feature_dim
)

verbosity_params = dict(
    debug_lvl = "warning"
)  

other_params = dict(
    device = "0",
    dtype = torch.float64,
    allow_tf32 = False
)

In [19]:
model_params["cache_size"] = 10000
data_params["specification"]["avg_within_class_degree"] = 1.58 * 2
data_params["specification"]["avg_between_class_degree"] = 0.37 * 2
other_params["device"] = 0
other_params["debug"] = False
certificate_params["n_adversarial"] = 10
certificate_params["delta"] = 0.05
certificate_params["method"] = "XXT"
certificate_params["perturbation_model"] = "linf"
certificate_params["cert_method"] = "ntk_bound"
verbosity_params["debug_lvl"] = "info"
model_params["regularizer"] = 10
model_params["solver"] = "cvxopt"
model_params["alpha_tol"] = 1e-4
model_params["bias"] = False
data_params["learning_setting"] = "inductive"
run(data_params, model_params, certificate_params, verbosity_params, other_params, seed)

2024-04-05 21:04:30 (INFO): Starting experiment exp_ntk_certify with configuration:
2024-04-05 21:04:30 (INFO): data_params: {'dataset': 'csbm', 'learning_setting': 'inductive', 'specification': {'classes': 2, 'n_trn_labeled': 40, 'n_trn_unlabeled': 0, 'n_val': 40, 'n_test': 200, 'sigma': 1, 'avg_within_class_degree': 3.16, 'avg_between_class_degree': 0.74, 'K': 1.5, 'seed': 0}}
2024-04-05 21:04:30 (INFO): model_params: {'label': 'GCN', 'model': 'GCN', 'normalization': 'row_normalization', 'depth': 1, 'regularizer': 10, 'pred_method': 'svm', 'cache_size': 10000, 'solver': 'cvxopt', 'alpha_tol': 0.0001, 'bias': False}
2024-04-05 21:04:30 (INFO): certification_params: {'n_adversarial': 10, 'perturbation_model': 'linf', 'delta': 0.05, 'method': 'XXT', 'cert_method': 'ntk_bound'}
2024-04-05 21:04:30 (INFO): verbosity_params: {'debug_lvl': 'info'}
2024-04-05 21:04:30 (INFO): other_params: {'device': 0, 'dtype': torch.float64, 'allow_tf32': False, 'debug': False}
2024-04-05 21:04:30 (INFO): 

CSBM mu:
[0.25 0.25 0.25 0.25 0.25 0.25 0.25 0.25 0.25]
X.mean() -0.015499045187653604
tensor([[ 8.6638,  1.8081,  2.7694,  ...,  1.4649,  2.9793,  0.1474],
        [ 1.8081,  3.8939,  2.6414,  ...,  0.8917,  0.4570,  2.2749],
        [ 2.7694,  2.6414, 12.6003,  ...,  0.8681,  1.2670,  2.2477],
        ...,
        [ 1.4649,  0.8917,  0.8681,  ...,  1.2364,  1.1845,  1.7045],
        [ 2.9793,  0.4570,  1.2670,  ...,  1.1845,  6.6676,  1.3267],
        [ 0.1474,  2.2749,  2.2477,  ...,  1.7045,  1.3267, 12.9359]],
       device='cuda:0', dtype=torch.float64)
     pcost       dcost       gap    pres   dres
 0:  1.2030e+02 -3.5362e+03  7e+03  4e-01  1e-14
 1:  1.3011e+02 -7.3849e+02  1e+03  3e-02  1e-14
 2:  2.0831e+01 -1.1037e+02  1e+02  2e-03  7e-15
 3: -8.2405e+00 -2.9364e+01  2e+01  1e-04  4e-15
 4: -1.3213e+01 -1.8695e+01  6e+00  3e-05  3e-15
 5: -1.4747e+01 -1.5646e+01  9e-01  3e-06  2e-15
 6: -1.5060e+01 -1.5148e+01  9e-02  2e-07  2e-15
 7: -1.5095e+01 -1.5097e+01  2e-03  3e-09  

{'accuracy': 0.8349999785423279,
 'accuracy_ub': 0.7549999952316284,
 'accuracy_lb': 0.8149999976158142,
 'accuracy_cert_trivial': 0.57,
 'accuracy_cert': 0.7699999809265137,
 'accuracy_cert_unrobust': 0.0,
 'min_ypred': -9.209222274211932,
 'max_ypred': 13.024179468177147,
 'min_ylb': -13.07503281996931,
 'max_ylb': 12.454546892162945,
 'min_yub': -8.565138014691824,
 'max_yub': 13.532818922559645,
 'avg_ntklb': 0.7796019890342774,
 'min_ntklb': -0.56791616023592,
 'max_ntklb': 16.832196933754503,
 'avg_ntkub': 0.8617887308830283,
 'min_ntkub': -0.4612999889266439,
 'max_ntkub': 16.832196933754503,
 'min_ntklabeled': -1.4790393185828268,
 'max_ntklabeled': 37.96431087152154,
 'avg_ntkunlabeled': 0.8023855998151816,
 'min_ntkunlabeled': -0.4612999889266439,
 'max_ntkunlabeled': 4.949783003985266,
 'cond': 17.094300822456614}

In [10]:
model_params["cache_size"] = 10000
data_params["specification"]["avg_within_class_degree"] = 1.58 * 2
data_params["specification"]["avg_between_class_degree"] = 0.37 * 2
other_params["device"] = 0
certificate_params["n_adversarial"] = 20
certificate_params["delta"] = 0.01
certificate_params["method"] = "XXT"
certificate_params["perturbation_model"] = "linf"
certificate_params["cert_method"] = "bilevel_svm"
verbosity_params["debug_lvl"] = "info"
model_params["regularizer"] = 0.01
model_params["solver"] = "sklea"
model_params["alpha_tol"] = 1e-4
model_params["bias"] = False
data_params["learning_setting"] = "transductive"
run(data_params, model_params, certificate_params, verbosity_params, other_params, seed)

2024-04-05 20:44:45 (INFO): Starting experiment exp_ntk_certify with configuration:
2024-04-05 20:44:45 (INFO): data_params: {'dataset': 'csbm', 'learning_setting': 'transductive', 'specification': {'classes': 2, 'n_trn_labeled': 40, 'n_trn_unlabeled': 0, 'n_val': 40, 'n_test': 200, 'sigma': 1, 'avg_within_class_degree': 3.16, 'avg_between_class_degree': 0.74, 'K': 1.5, 'seed': 0}}
2024-04-05 20:44:45 (INFO): model_params: {'label': 'GCN', 'model': 'GCN', 'normalization': 'row_normalization', 'depth': 1, 'regularizer': 0.01, 'pred_method': 'svm', 'cache_size': 10000, 'solver': 'sklea', 'alpha_tol': 0.0001, 'bias': False}
2024-04-05 20:44:45 (INFO): certification_params: {'n_adversarial': 20, 'perturbation_model': 'linf', 'delta': 0.01, 'method': 'XXT', 'cert_method': 'bilevel_svm'}
2024-04-05 20:44:45 (INFO): verbosity_params: {'debug_lvl': 'info'}
2024-04-05 20:44:45 (INFO): other_params: {'device': 0, 'dtype': torch.float64, 'allow_tf32': False, 'debug': True}
2024-04-05 20:44:45 (IN

CSBM mu:
[0.25 0.25 0.25 0.25 0.25 0.25 0.25 0.25 0.25]
X.mean() -0.015499045187653604
Sig.mean(): 0.05107504648491424
Sig.min(): -5.287786267364439
Sig.max(): 8.416098466877251
Depth 0
E_der.min(): 0.09049594600646133
E_der.max(): 1.0
Sig.mean(): 0.7043144430678637
Sig.min(): 0.09446270523894534
Sig.max(): 8.416098466877251
tensor([[3.0921, 0.5617, 2.1448,  ..., 0.0152, 1.0838, 0.7411],
        [0.5617, 1.9085, 0.7784,  ..., 1.3111, 0.1945, 0.2661],
        [2.1448, 0.7784, 2.5435,  ..., 0.5006, 0.8922, 0.8812],
        ...,
        [0.0152, 1.3111, 0.5006,  ..., 6.4818, 0.1579, 2.1692],
        [1.0838, 0.1945, 0.8922,  ..., 0.1579, 0.8181, 0.5312],
        [0.7411, 0.2661, 0.8812,  ..., 2.1692, 0.5312, 1.8187]],
       device='cuda:0', dtype=torch.float64)


AssertionError: Solver not found