In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import torch
import numpy as np
from exp_ntk_attack_backdoor import run
from exp_ntk_attack import run as run_2

In [3]:
seed = 0

data_params = dict(
    dataset = "csbm",
    learning_setting = "transductive", # or "transdructive"
    specification = dict(
        classes = 2,
        n_trn_labeled = 40, 
        n_trn_unlabeled = 0,
        n_val = 40,
        n_test = 120,
        sigma = 1,
        avg_within_class_degree = 1.58 * 2,
        avg_between_class_degree = 0.37 * 2,
        K = 1.5,
        seed = 0 # used to generate the dataset & data split
    )
)

model_params = dict(
    label = "GCN",
    model = "GCN",
    normalization = "row_normalization",
    depth = 1,
    #regularizer = 1e-8
    regularizer = 1,
    pred_method = "svm",
    activation = "linear"
)

attack_params = dict(
    attack = "apgd",
    n_adversarial = 1, # number adversarial nodes
    perturbation_model = "linf",
    delta = 0.01 # l0: local budget = delta * feature_dim
)

verbosity_params = dict(
    debug_lvl = "warning"
)  

other_params = dict(
    device = "cpu",
    dtype = torch.float64,
    allow_tf32 = False,
    store_attack_curve = True, # If the "learning curve" of the attack should be saved to mongodb
    store_first_iter = 100, # Always save first 100 iterations of attack a particular node
    store_every_X_iter = 10, # Afterwards, save every 10th iteration of attack
)

In [69]:
%reload_ext autoreload
#model_params["cache_size"] = 10000
seed = 4
data_params["specification"]["seed"] = seed
other_params["device"] = "cpu"
other_params["debug"] = False
attack_params["n_adversarial"] = 16
attack_params["delta"] = 0.5
attack_params["max_iter"] = 100
attack_params["eta"] = 2
attack_params["n_restarts"] = 0
attack_params["attack"] = "cgba"
attack_params["delta_absolute"] = False
attack_params["normalize_grad"] = True
attack_params["perturbation_model"] = "linf"
attack_params["attack_nodes"] = "train_val"
attack_params["attack"] = "cgba"
attack_params["trigger_size"] = 0.5
verbosity_params["debug_lvl"] = "info"
model_params["regularizer"] = 0.01
model_params["solver"] = "qplayer"
model_params["alpha_tol"] = 1e-4
model_params["bias"] = False
data_params["learning_setting"] = "transductive"
other_params["max_logging_iters"] = 0
other_params["store_attack_curve"] = False
run(data_params, model_params, attack_params, verbosity_params, other_params, seed)

2024-11-18 20:52:23 (INFO): Starting experiment exp_ntk_attack_backdoor with configuration:
2024-11-18 20:52:23 (INFO): data_params: {'dataset': 'csbm', 'learning_setting': 'transductive', 'specification': {'classes': 2, 'n_trn_labeled': 40, 'n_trn_unlabeled': 0, 'n_val': 40, 'n_test': 120, 'sigma': 1, 'avg_within_class_degree': 3.16, 'avg_between_class_degree': 0.74, 'K': 1.5, 'seed': 4}}
2024-11-18 20:52:23 (INFO): model_params: {'label': 'GCN', 'model': 'GCN', 'normalization': 'row_normalization', 'depth': 1, 'regularizer': 0.01, 'pred_method': 'svm', 'activation': 'linear', 'solver': 'qplayer', 'alpha_tol': 0.0001, 'bias': False}
2024-11-18 20:52:23 (INFO): certification_params: {'attack': 'cgba', 'n_adversarial': 16, 'perturbation_model': 'linf', 'delta': 0.5, 'max_iter': 100, 'eta': 2, 'n_restarts': 0, 'delta_absolute': False, 'normalize_grad': True, 'attack_nodes': 'train_val', 'gradient_method': 'exact', 'trigger_size': 0.5}
2024-11-18 20:52:23 (INFO): verbosity_params: {'debug

2024-11-18 20:52:23 (INFO): y_pert: -0.40944370; y_clean: -0.40280318; Pert: False; Correct Clean: True; Total Pert: 0 Total Clean: 2.0; Total: 2
2024-11-18 20:52:23 (INFO): y_pert: 0.23457019; y_clean: 0.23098117; Pert: False; Correct Clean: False; Total Pert: 0 Total Clean: 2.0; Total: 3
2024-11-18 20:52:23 (INFO): y_pert: -0.27365025; y_clean: -0.27449022; Pert: False; Correct Clean: True; Total Pert: 0 Total Clean: 3.0; Total: 4
2024-11-18 20:52:23 (INFO): y_pert: 0.05785223; y_clean: 0.03937141; Pert: False; Correct Clean: False; Total Pert: 0 Total Clean: 3.0; Total: 5
2024-11-18 20:52:23 (INFO): y_pert: -1.31351887; y_clean: -1.29504287; Pert: False; Correct Clean: True; Total Pert: 0 Total Clean: 4.0; Total: 6
2024-11-18 20:52:23 (INFO): y_pert: -0.42482350; y_clean: -0.42637824; Pert: False; Correct Clean: True; Total Pert: 0 Total Clean: 5.0; Total: 7
2024-11-18 20:52:23 (INFO): y_pert: -0.60159372; y_clean: -0.59101340; Pert: False; Correct Clean: True; Total Pert: 0 Total C

CSBM mu:
[0.28347334 0.28347334 0.28347334 0.28347334 0.28347334 0.28347334
 0.28347334]


2024-11-18 20:52:23 (INFO): y_pert: 0.28996693; y_clean: 0.28568287; Pert: False; Correct Clean: False; Total Pert: 0 Total Clean: 6.0; Total: 10
2024-11-18 20:52:23 (INFO): y_pert: -0.18379349; y_clean: -0.18417727; Pert: False; Correct Clean: True; Total Pert: 0 Total Clean: 7.0; Total: 11
2024-11-18 20:52:23 (INFO): y_pert: -0.24296074; y_clean: -0.24010406; Pert: False; Correct Clean: True; Total Pert: 0 Total Clean: 8.0; Total: 12
2024-11-18 20:52:23 (INFO): y_pert: -0.06879295; y_clean: -0.07521182; Pert: False; Correct Clean: True; Total Pert: 0 Total Clean: 9.0; Total: 13
2024-11-18 20:52:23 (INFO): y_pert: -0.02522049; y_clean: -0.02377026; Pert: False; Correct Clean: True; Total Pert: 0 Total Clean: 10.0; Total: 14
2024-11-18 20:52:23 (INFO): y_pert: -0.47185877; y_clean: -0.47373751; Pert: False; Correct Clean: True; Total Pert: 0 Total Clean: 11.0; Total: 15
2024-11-18 20:52:23 (INFO): y_pert: -0.00285600; y_clean: -0.00711643; Pert: False; Correct Clean: True; Total Pert: 

{'accuracy_test': 0.825,
 'robust_accuracy_test': 0.8166666666666667,
 'pert_success_ratio': 0.008333333333333333,
 'delta_absolute': 0.2835,
 'y_true_cls': [-1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1],
 'y_pred_logit': [-0.3309660155302237,
  -0.40280318072984583,
  0.23098116725016,
  -0.2744902249940355,
  0.03937140701925615,
  -1.2950428714651083,
  -0.4263782376921144,
  -0.5910134

In [58]:
%reload_ext autoreload
#model_params["cache_size"] = 10000
seed = 4
data_params["specification"]["seed"] = seed
other_params["device"] = "cpu"
other_params["debug"] = False
attack_params["n_adversarial"] = 16
attack_params["delta"] = 10
attack_params["max_iter"] = 100
attack_params["eta"] = 2
attack_params["n_restarts"] = 0
attack_params["attack"] = "cgba"
attack_params["delta_absolute"] = False
attack_params["normalize_grad"] = True
attack_params["perturbation_model"] = "linf"
attack_params["attack_nodes"] = "train_val"
attack_params["attack"] = "cgba"
attack_params["trigger_size"] = 1
verbosity_params["debug_lvl"] = "info"
model_params["regularizer"] = 0.01
model_params["solver"] = "qplayer"
model_params["alpha_tol"] = 1e-4
model_params["bias"] = False
data_params["learning_setting"] = "transductive"
other_params["max_logging_iters"] = 0
other_params["store_attack_curve"] = False
run(data_params, model_params, attack_params, verbosity_params, other_params, seed)

2024-11-18 20:47:11 (INFO): Starting experiment exp_ntk_attack_backdoor with configuration:
2024-11-18 20:47:11 (INFO): data_params: {'dataset': 'csbm', 'learning_setting': 'transductive', 'specification': {'classes': 2, 'n_trn_labeled': 40, 'n_trn_unlabeled': 0, 'n_val': 40, 'n_test': 120, 'sigma': 1, 'avg_within_class_degree': 3.16, 'avg_between_class_degree': 0.74, 'K': 1.5, 'seed': 4}}
2024-11-18 20:47:11 (INFO): model_params: {'label': 'GCN', 'model': 'GCN', 'normalization': 'row_normalization', 'depth': 1, 'regularizer': 0.01, 'pred_method': 'svm', 'activation': 'linear', 'solver': 'qplayer', 'alpha_tol': 0.0001, 'bias': False}
2024-11-18 20:47:11 (INFO): certification_params: {'attack': 'cgba', 'n_adversarial': 16, 'perturbation_model': 'linf', 'delta': 10, 'max_iter': 100, 'eta': 2, 'n_restarts': 0, 'delta_absolute': False, 'normalize_grad': True, 'attack_nodes': 'train_val', 'gradient_method': 'exact', 'trigger_size': 1}
2024-11-18 20:47:11 (INFO): verbosity_params: {'debug_lv

CSBM mu:
[0.28347334 0.28347334 0.28347334 0.28347334 0.28347334 0.28347334
 0.28347334]
tensor([ 1.3514,  1.4606, -0.7613, -0.3823, -1.3013,  0.0810, -0.8410],
       dtype=torch.float64)
tensor([[ 1.3514,  1.4606, -0.8410, -0.3823,  0.0810, -1.3013, -0.7613]],
       dtype=torch.float64)
tensor([ 1.3514,  1.4606, -0.7613, -0.3823, -1.3013,  0.0810, -0.8410],
       dtype=torch.float64)
tensor([[ 1.3514,  1.4606, -0.8410, -0.3823,  0.0810, -1.3013, -0.7613]],
       dtype=torch.float64)
tensor([ 1.3514,  1.4606, -0.7613, -0.3823, -1.3013,  0.0810, -0.8410],
       dtype=torch.float64)
tensor([[ 1.3514,  1.4606, -0.8410, -0.3823,  0.0810, -1.3013, -0.7613]],
       dtype=torch.float64)
tensor([ 1.3514,  1.4606, -0.7613, -0.3823, -1.3013,  0.0810, -0.8410],
       dtype=torch.float64)
tensor([[ 1.3514,  1.4606, -0.8410, -0.3823,  0.0810, -1.3013, -0.7613]],
       dtype=torch.float64)
tensor([ 1.3514,  1.4606, -0.7613, -0.3823, -1.3013,  0.0810, -0.8410],
       dtype=torch.float64)
ten

2024-11-18 20:47:11 (INFO): y_pert: 0.00346873; y_clean: -0.07521182; Pert: True; Correct Clean: True; Total Pert: 1 Total Clean: 9.0; Total: 13
2024-11-18 20:47:11 (INFO): y_pert: -0.05737826; y_clean: -0.02377026; Pert: False; Correct Clean: True; Total Pert: 1 Total Clean: 10.0; Total: 14
2024-11-18 20:47:11 (INFO): y_pert: -0.43451176; y_clean: -0.47373751; Pert: False; Correct Clean: True; Total Pert: 1 Total Clean: 11.0; Total: 15
2024-11-18 20:47:11 (INFO): y_pert: 0.03658813; y_clean: -0.00711643; Pert: True; Correct Clean: True; Total Pert: 2 Total Clean: 12.0; Total: 16
2024-11-18 20:47:11 (INFO): y_pert: -0.10612501; y_clean: -0.15609097; Pert: False; Correct Clean: True; Total Pert: 2 Total Clean: 13.0; Total: 17
2024-11-18 20:47:11 (INFO): y_pert: -0.32050691; y_clean: -0.39961287; Pert: False; Correct Clean: True; Total Pert: 2 Total Clean: 14.0; Total: 18
2024-11-18 20:47:11 (INFO): y_pert: -0.07579286; y_clean: -0.10723278; Pert: False; Correct Clean: True; Total Pert: 

tensor([ 1.3514,  1.4606, -0.7613, -0.3823, -1.3013,  0.0810, -0.8410],
       dtype=torch.float64)
tensor([[ 1.3514,  1.4606, -0.8410, -0.3823,  0.0810, -1.3013, -0.7613]],
       dtype=torch.float64)
tensor([ 1.3514,  1.4606, -0.7613, -0.3823, -1.3013,  0.0810, -0.8410],
       dtype=torch.float64)
tensor([[ 1.3514,  1.4606, -0.8410, -0.3823,  0.0810, -1.3013, -0.7613]],
       dtype=torch.float64)
tensor([ 1.3514,  1.4606, -0.7613, -0.3823, -1.3013,  0.0810, -0.8410],
       dtype=torch.float64)
tensor([ 1.3514,  1.4606, -0.7613, -0.3823, -1.3013,  0.0810, -0.8410],
       dtype=torch.float64)
tensor([[ 1.3514,  1.4606, -0.8410, -0.3823,  0.0810, -1.3013, -0.7613]],
       dtype=torch.float64)
tensor([ 1.3514,  1.4606, -0.7613, -0.3823, -1.3013,  0.0810, -0.8410],
       dtype=torch.float64)
tensor([[ 1.3514,  1.4606, -0.8410, -0.3823,  0.0810, -1.3013, -0.7613]],
       dtype=torch.float64)
tensor([ 1.3514,  1.4606, -0.7613, -0.3823, -1.3013,  0.0810, -0.8410],
       dtype=torch.f

2024-11-18 20:47:11 (INFO): y_pert: -0.63214729; y_clean: -0.72768301; Pert: False; Correct Clean: True; Total Pert: 5 Total Clean: 23.0; Total: 30
2024-11-18 20:47:11 (INFO): y_pert: 0.44718314; y_clean: 0.47174995; Pert: False; Correct Clean: False; Total Pert: 5 Total Clean: 23.0; Total: 31
2024-11-18 20:47:12 (INFO): y_pert: -0.55994943; y_clean: -0.60880681; Pert: False; Correct Clean: True; Total Pert: 5 Total Clean: 24.0; Total: 32
2024-11-18 20:47:12 (INFO): y_pert: -0.42321059; y_clean: -0.46763496; Pert: False; Correct Clean: True; Total Pert: 5 Total Clean: 25.0; Total: 33
2024-11-18 20:47:12 (INFO): y_pert: 0.02509598; y_clean: -0.01870317; Pert: True; Correct Clean: True; Total Pert: 6 Total Clean: 26.0; Total: 34
2024-11-18 20:47:12 (INFO): y_pert: -0.23046953; y_clean: -0.19369136; Pert: False; Correct Clean: True; Total Pert: 6 Total Clean: 27.0; Total: 35
2024-11-18 20:47:12 (INFO): y_pert: -0.33094207; y_clean: -0.36715678; Pert: False; Correct Clean: True; Total Pert

tensor([[ 1.3514,  1.4606, -0.8410, -0.3823,  0.0810, -1.3013, -0.7613]],
       dtype=torch.float64)
tensor([ 1.3514,  1.4606, -0.7613, -0.3823, -1.3013,  0.0810, -0.8410],
       dtype=torch.float64)
tensor([[ 1.3514,  1.4606, -0.8410, -0.3823,  0.0810, -1.3013, -0.7613]],
       dtype=torch.float64)
tensor([ 1.3514,  1.4606, -0.7613, -0.3823, -1.3013,  0.0810, -0.8410],
       dtype=torch.float64)
tensor([[ 1.3514,  1.4606, -0.8410, -0.3823,  0.0810, -1.3013, -0.7613]],
       dtype=torch.float64)
tensor([ 1.3514,  1.4606, -0.7613, -0.3823, -1.3013,  0.0810, -0.8410],
       dtype=torch.float64)
tensor([[ 1.3514,  1.4606, -0.8410, -0.3823,  0.0810, -1.3013, -0.7613]],
       dtype=torch.float64)
tensor([ 1.3514,  1.4606, -0.7613, -0.3823, -1.3013,  0.0810, -0.8410],
       dtype=torch.float64)
tensor([ 1.3514,  1.4606, -0.7613, -0.3823, -1.3013,  0.0810, -0.8410],
       dtype=torch.float64)
tensor([[ 1.3514,  1.4606, -0.8410, -0.3823,  0.0810, -1.3013, -0.7613]],
       dtype=torch

2024-11-18 20:47:12 (INFO): y_pert: -0.03417621; y_clean: -0.13620362; Pert: False; Correct Clean: True; Total Pert: 6 Total Clean: 36.0; Total: 44
2024-11-18 20:47:12 (INFO): y_pert: -0.12161371; y_clean: -0.16823350; Pert: False; Correct Clean: True; Total Pert: 6 Total Clean: 37.0; Total: 45
2024-11-18 20:47:12 (INFO): y_pert: -0.48713267; y_clean: -0.48192223; Pert: False; Correct Clean: True; Total Pert: 6 Total Clean: 38.0; Total: 46
2024-11-18 20:47:12 (INFO): y_pert: 0.06956074; y_clean: 0.09717641; Pert: False; Correct Clean: False; Total Pert: 6 Total Clean: 38.0; Total: 47
2024-11-18 20:47:12 (INFO): y_pert: 0.75414417; y_clean: 0.95867491; Pert: False; Correct Clean: False; Total Pert: 6 Total Clean: 38.0; Total: 48
2024-11-18 20:47:12 (INFO): y_pert: -0.61373111; y_clean: -0.67008065; Pert: False; Correct Clean: True; Total Pert: 6 Total Clean: 39.0; Total: 49
2024-11-18 20:47:12 (INFO): y_pert: -1.03605119; y_clean: -0.90394009; Pert: False; Correct Clean: True; Total Per

tensor([ 1.3514,  1.4606, -0.7613, -0.3823, -1.3013,  0.0810, -0.8410],
       dtype=torch.float64)
tensor([[ 1.3514,  1.4606, -0.8410, -0.3823,  0.0810, -1.3013, -0.7613]],
       dtype=torch.float64)
tensor([ 1.3514,  1.4606, -0.7613, -0.3823, -1.3013,  0.0810, -0.8410],
       dtype=torch.float64)
tensor([[ 1.3514,  1.4606, -0.8410, -0.3823,  0.0810, -1.3013, -0.7613]],
       dtype=torch.float64)
tensor([ 1.3514,  1.4606, -0.7613, -0.3823, -1.3013,  0.0810, -0.8410],
       dtype=torch.float64)
tensor([[ 1.3514,  1.4606, -0.8410, -0.3823,  0.0810, -1.3013, -0.7613]],
       dtype=torch.float64)
tensor([ 1.3514,  1.4606, -0.7613, -0.3823, -1.3013,  0.0810, -0.8410],
       dtype=torch.float64)
tensor([[ 1.3514,  1.4606, -0.8410, -0.3823,  0.0810, -1.3013, -0.7613]],
       dtype=torch.float64)
tensor([ 1.3514,  1.4606, -0.7613, -0.3823, -1.3013,  0.0810, -0.8410],
       dtype=torch.float64)
tensor([[ 1.3514,  1.4606, -0.8410, -0.3823,  0.0810, -1.3013, -0.7613]],
       dtype=torch

2024-11-18 20:47:12 (INFO): y_pert: 0.02726413; y_clean: -0.01443550; Pert: True; Correct Clean: True; Total Pert: 7 Total Clean: 41.0; Total: 52
2024-11-18 20:47:12 (INFO): y_pert: -0.30681115; y_clean: -0.32230003; Pert: False; Correct Clean: True; Total Pert: 7 Total Clean: 42.0; Total: 53
2024-11-18 20:47:12 (INFO): y_pert: -0.46870885; y_clean: -0.44745144; Pert: False; Correct Clean: True; Total Pert: 7 Total Clean: 43.0; Total: 54
2024-11-18 20:47:12 (INFO): y_pert: -0.22353474; y_clean: -0.25905043; Pert: False; Correct Clean: True; Total Pert: 7 Total Clean: 44.0; Total: 55
2024-11-18 20:47:12 (INFO): y_pert: -0.62378451; y_clean: -0.52104680; Pert: False; Correct Clean: True; Total Pert: 7 Total Clean: 45.0; Total: 56
2024-11-18 20:47:12 (INFO): y_pert: 0.38472099; y_clean: 0.37428311; Pert: False; Correct Clean: True; Total Pert: 7 Total Clean: 46.0; Total: 57
2024-11-18 20:47:12 (INFO): y_pert: 0.18325744; y_clean: 0.23176553; Pert: False; Correct Clean: True; Total Pert: 7

tensor([ 1.3514,  1.4606, -0.7613, -0.3823, -1.3013,  0.0810, -0.8410],
       dtype=torch.float64)
tensor([[ 1.3514,  1.4606, -0.8410, -0.3823,  0.0810, -1.3013, -0.7613]],
       dtype=torch.float64)
tensor([ 1.3514,  1.4606, -0.7613, -0.3823, -1.3013,  0.0810, -0.8410],
       dtype=torch.float64)
tensor([[ 1.3514,  1.4606, -0.8410, -0.3823,  0.0810, -1.3013, -0.7613]],
       dtype=torch.float64)
tensor([ 1.3514,  1.4606, -0.7613, -0.3823, -1.3013,  0.0810, -0.8410],
       dtype=torch.float64)
tensor([[ 1.3514,  1.4606, -0.8410, -0.3823,  0.0810, -1.3013, -0.7613]],
       dtype=torch.float64)
tensor([ 1.3514,  1.4606, -0.7613, -0.3823, -1.3013,  0.0810, -0.8410],
       dtype=torch.float64)
tensor([[ 1.3514,  1.4606, -0.8410, -0.3823,  0.0810, -1.3013, -0.7613]],
       dtype=torch.float64)
tensor([ 0.8148,  0.2770, -1.4201,  0.7793, -0.3112,  1.4972, -0.9924],
       dtype=torch.float64)
tensor([[-0.3112,  1.4972,  0.7793, -0.9924,  0.2770, -1.4201,  0.8148]],
       dtype=torch

2024-11-18 20:47:12 (INFO): y_pert: 0.69928159; y_clean: 0.70826200; Pert: False; Correct Clean: True; Total Pert: 7 Total Clean: 50.0; Total: 61
2024-11-18 20:47:12 (INFO): y_pert: 0.68739507; y_clean: 0.74711336; Pert: False; Correct Clean: True; Total Pert: 7 Total Clean: 51.0; Total: 62
2024-11-18 20:47:12 (INFO): y_pert: 0.32838548; y_clean: 0.34959688; Pert: False; Correct Clean: True; Total Pert: 7 Total Clean: 52.0; Total: 63
2024-11-18 20:47:12 (INFO): y_pert: 0.30360151; y_clean: 0.27693833; Pert: False; Correct Clean: True; Total Pert: 7 Total Clean: 53.0; Total: 64
2024-11-18 20:47:12 (INFO): y_pert: 0.31402059; y_clean: 0.41196922; Pert: False; Correct Clean: True; Total Pert: 7 Total Clean: 54.0; Total: 65
2024-11-18 20:47:12 (INFO): y_pert: 0.63569755; y_clean: 0.64305208; Pert: False; Correct Clean: True; Total Pert: 7 Total Clean: 55.0; Total: 66
2024-11-18 20:47:12 (INFO): y_pert: 0.61758450; y_clean: 0.61693337; Pert: False; Correct Clean: True; Total Pert: 7 Total C

tensor([ 0.8148,  0.2770, -1.4201,  0.7793, -0.3112,  1.4972, -0.9924],
       dtype=torch.float64)
tensor([[-0.3112,  1.4972,  0.7793, -0.9924,  0.2770, -1.4201,  0.8148]],
       dtype=torch.float64)
tensor([ 0.8148,  0.2770, -1.4201,  0.7793, -0.3112,  1.4972, -0.9924],
       dtype=torch.float64)
tensor([[-0.3112,  1.4972,  0.7793, -0.9924,  0.2770, -1.4201,  0.8148]],
       dtype=torch.float64)
tensor([ 0.8148,  0.2770, -1.4201,  0.7793, -0.3112,  1.4972, -0.9924],
       dtype=torch.float64)
tensor([[-0.3112,  1.4972,  0.7793, -0.9924,  0.2770, -1.4201,  0.8148]],
       dtype=torch.float64)
tensor([ 0.8148,  0.2770, -1.4201,  0.7793, -0.3112,  1.4972, -0.9924],
       dtype=torch.float64)
tensor([[-0.3112,  1.4972,  0.7793, -0.9924,  0.2770, -1.4201,  0.8148]],
       dtype=torch.float64)
tensor([ 0.8148,  0.2770, -1.4201,  0.7793, -0.3112,  1.4972, -0.9924],
       dtype=torch.float64)
tensor([[-0.3112,  1.4972,  0.7793, -0.9924,  0.2770, -1.4201,  0.8148]],
       dtype=torch

2024-11-18 20:47:12 (INFO): y_pert: 0.37395290; y_clean: 0.39192067; Pert: False; Correct Clean: True; Total Pert: 7 Total Clean: 62.0; Total: 74
2024-11-18 20:47:12 (INFO): y_pert: -0.42373738; y_clean: -0.42658982; Pert: False; Correct Clean: False; Total Pert: 7 Total Clean: 62.0; Total: 75
2024-11-18 20:47:12 (INFO): y_pert: 0.10452260; y_clean: 0.14175719; Pert: False; Correct Clean: True; Total Pert: 7 Total Clean: 63.0; Total: 76
2024-11-18 20:47:12 (INFO): y_pert: 0.37567090; y_clean: 0.37080885; Pert: False; Correct Clean: True; Total Pert: 7 Total Clean: 64.0; Total: 77
2024-11-18 20:47:12 (INFO): y_pert: 0.07590529; y_clean: 0.14329675; Pert: False; Correct Clean: True; Total Pert: 7 Total Clean: 65.0; Total: 78
2024-11-18 20:47:12 (INFO): y_pert: 0.41983766; y_clean: 0.45116894; Pert: False; Correct Clean: True; Total Pert: 7 Total Clean: 66.0; Total: 79
2024-11-18 20:47:12 (INFO): y_pert: 0.23076710; y_clean: 0.21921341; Pert: False; Correct Clean: True; Total Pert: 7 Tota

tensor([[-0.3112,  1.4972,  0.7793, -0.9924,  0.2770, -1.4201,  0.8148]],
       dtype=torch.float64)
tensor([ 0.8148,  0.2770, -1.4201,  0.7793, -0.3112,  1.4972, -0.9924],
       dtype=torch.float64)
tensor([[-0.3112,  1.4972,  0.7793, -0.9924,  0.2770, -1.4201,  0.8148]],
       dtype=torch.float64)
tensor([ 0.8148,  0.2770, -1.4201,  0.7793, -0.3112,  1.4972, -0.9924],
       dtype=torch.float64)
tensor([[-0.3112,  1.4972,  0.7793, -0.9924,  0.2770, -1.4201,  0.8148]],
       dtype=torch.float64)
tensor([ 0.8148,  0.2770, -1.4201,  0.7793, -0.3112,  1.4972, -0.9924],
       dtype=torch.float64)
tensor([[-0.3112,  1.4972,  0.7793, -0.9924,  0.2770, -1.4201,  0.8148]],
       dtype=torch.float64)
tensor([ 0.8148,  0.2770, -1.4201,  0.7793, -0.3112,  1.4972, -0.9924],
       dtype=torch.float64)
tensor([[-0.3112,  1.4972,  0.7793, -0.9924,  0.2770, -1.4201,  0.8148]],
       dtype=torch.float64)
tensor([ 0.8148,  0.2770, -1.4201,  0.7793, -0.3112,  1.4972, -0.9924],
       dtype=torch

2024-11-18 20:47:13 (INFO): y_pert: 0.31035559; y_clean: 0.32272179; Pert: False; Correct Clean: True; Total Pert: 7 Total Clean: 74.0; Total: 89
2024-11-18 20:47:13 (INFO): y_pert: -0.07027685; y_clean: -0.03806918; Pert: False; Correct Clean: False; Total Pert: 7 Total Clean: 74.0; Total: 90
2024-11-18 20:47:13 (INFO): y_pert: -0.36576407; y_clean: -0.33968542; Pert: False; Correct Clean: False; Total Pert: 7 Total Clean: 74.0; Total: 91
2024-11-18 20:47:13 (INFO): y_pert: 0.04477883; y_clean: -0.02267109; Pert: True; Correct Clean: False; Total Pert: 8 Total Clean: 74.0; Total: 92
2024-11-18 20:47:13 (INFO): y_pert: 0.40189222; y_clean: 0.52272643; Pert: False; Correct Clean: True; Total Pert: 8 Total Clean: 75.0; Total: 93
2024-11-18 20:47:13 (INFO): y_pert: 0.29576932; y_clean: 0.31319736; Pert: False; Correct Clean: True; Total Pert: 8 Total Clean: 76.0; Total: 94
2024-11-18 20:47:13 (INFO): y_pert: 0.40990692; y_clean: 0.42600962; Pert: False; Correct Clean: True; Total Pert: 8 

tensor([[-0.3112,  1.4972,  0.7793, -0.9924,  0.2770, -1.4201,  0.8148]],
       dtype=torch.float64)
tensor([ 0.8148,  0.2770, -1.4201,  0.7793, -0.3112,  1.4972, -0.9924],
       dtype=torch.float64)
tensor([[-0.3112,  1.4972,  0.7793, -0.9924,  0.2770, -1.4201,  0.8148]],
       dtype=torch.float64)
tensor([ 0.8148,  0.2770, -1.4201,  0.7793, -0.3112,  1.4972, -0.9924],
       dtype=torch.float64)
tensor([[-0.3112,  1.4972,  0.7793, -0.9924,  0.2770, -1.4201,  0.8148]],
       dtype=torch.float64)
tensor([ 0.8148,  0.2770, -1.4201,  0.7793, -0.3112,  1.4972, -0.9924],
       dtype=torch.float64)
tensor([ 0.8148,  0.2770, -1.4201,  0.7793, -0.3112,  1.4972, -0.9924],
       dtype=torch.float64)
tensor([[-0.3112,  1.4972,  0.7793, -0.9924,  0.2770, -1.4201,  0.8148]],
       dtype=torch.float64)
tensor([ 0.8148,  0.2770, -1.4201,  0.7793, -0.3112,  1.4972, -0.9924],
       dtype=torch.float64)
tensor([[-0.3112,  1.4972,  0.7793, -0.9924,  0.2770, -1.4201,  0.8148]],
       dtype=torch

2024-11-18 20:47:13 (INFO): y_pert: 0.20090943; y_clean: 0.16032147; Pert: False; Correct Clean: True; Total Pert: 8 Total Clean: 85.0; Total: 104
2024-11-18 20:47:13 (INFO): y_pert: 0.61340690; y_clean: 0.53418744; Pert: False; Correct Clean: True; Total Pert: 8 Total Clean: 86.0; Total: 105
2024-11-18 20:47:13 (INFO): y_pert: 0.41092524; y_clean: 0.37342103; Pert: False; Correct Clean: True; Total Pert: 8 Total Clean: 87.0; Total: 106
2024-11-18 20:47:13 (INFO): y_pert: 0.25317825; y_clean: 0.28185781; Pert: False; Correct Clean: True; Total Pert: 8 Total Clean: 88.0; Total: 107
2024-11-18 20:47:13 (INFO): y_pert: 0.40173364; y_clean: 0.40789428; Pert: False; Correct Clean: True; Total Pert: 8 Total Clean: 89.0; Total: 108
2024-11-18 20:47:13 (INFO): y_pert: 0.22086502; y_clean: 0.32851797; Pert: False; Correct Clean: True; Total Pert: 8 Total Clean: 90.0; Total: 109
2024-11-18 20:47:13 (INFO): y_pert: -0.00606036; y_clean: 0.00170415; Pert: True; Correct Clean: True; Total Pert: 9 T

tensor([ 0.8148,  0.2770, -1.4201,  0.7793, -0.3112,  1.4972, -0.9924],
       dtype=torch.float64)
tensor([[-0.3112,  1.4972,  0.7793, -0.9924,  0.2770, -1.4201,  0.8148]],
       dtype=torch.float64)
tensor([ 0.8148,  0.2770, -1.4201,  0.7793, -0.3112,  1.4972, -0.9924],
       dtype=torch.float64)
tensor([[-0.3112,  1.4972,  0.7793, -0.9924,  0.2770, -1.4201,  0.8148]],
       dtype=torch.float64)
tensor([ 0.8148,  0.2770, -1.4201,  0.7793, -0.3112,  1.4972, -0.9924],
       dtype=torch.float64)
tensor([[-0.3112,  1.4972,  0.7793, -0.9924,  0.2770, -1.4201,  0.8148]],
       dtype=torch.float64)
tensor([ 0.8148,  0.2770, -1.4201,  0.7793, -0.3112,  1.4972, -0.9924],
       dtype=torch.float64)
tensor([[-0.3112,  1.4972,  0.7793, -0.9924,  0.2770, -1.4201,  0.8148]],
       dtype=torch.float64)
tensor([ 0.8148,  0.2770, -1.4201,  0.7793, -0.3112,  1.4972, -0.9924],
       dtype=torch.float64)
tensor([[-0.3112,  1.4972,  0.7793, -0.9924,  0.2770, -1.4201,  0.8148]],
       dtype=torch

2024-11-18 20:47:13 (INFO): y_pert: 0.66603338; y_clean: 0.75517779; Pert: False; Correct Clean: True; Total Pert: 9 Total Clean: 99.0; Total: 120
2024-11-18 20:47:13 (INFO): Clean Accuracy: 0.82
2024-11-18 20:47:13 (INFO): Robust Accuracy: 0.78
2024-11-18 20:47:13 (INFO): % of Successfull Perturbations: 0.07


tensor([[-0.3112,  1.4972,  0.7793, -0.9924,  0.2770, -1.4201,  0.8148]],
       dtype=torch.float64)


{'accuracy_test': 0.825,
 'robust_accuracy_test': 0.775,
 'pert_success_ratio': 0.075,
 'delta_absolute': 5.6695,
 'y_true_cls': [-1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1],
 'y_pred_logit': [-0.3309660155302237,
  -0.40280318072984583,
  0.23098116725016,
  -0.2744902249940355,
  0.03937140701925615,
  -1.2950428714651083,
  -0.4263782376921144,
  -0.5910134007602955,
  0.1680520165816

In [9]:
# with evasion = False
%reload_ext autoreload
#model_params["cache_size"] = 10000
seed = 4
data_params["specification"]["seed"] = seed
other_params["device"] = "cpu"
other_params["debug"] = False
attack_params["n_adversarial"] = 24
attack_params["delta"] = 0.5
attack_params["max_iter"] = 100
attack_params["eta"] = 2
attack_params["n_restarts"] = 0
attack_params["attack"] = "apgd"
attack_params["delta_absolute"] = False
attack_params["normalize_grad"] = True
attack_params["perturbation_model"] = "linf"
attack_params["attack_nodes"] = "test"
attack_params["gradient_method"] = "exact"
verbosity_params["debug_lvl"] = "info"
model_params["regularizer"] = 0.01
model_params["solver"] = "qplayer"
model_params["alpha_tol"] = 1e-4
model_params["bias"] = False
data_params["learning_setting"] = "transductive"
other_params["max_logging_iters"] = 0
other_params["store_attack_curve"] = False
run(data_params, model_params, attack_params, verbosity_params, other_params, seed)

2024-11-18 20:17:54 (INFO): Starting experiment exp_ntk_attack_backdoor with configuration:
2024-11-18 20:17:54 (INFO): data_params: {'dataset': 'csbm', 'learning_setting': 'transductive', 'specification': {'classes': 2, 'n_trn_labeled': 40, 'n_trn_unlabeled': 0, 'n_val': 40, 'n_test': 120, 'sigma': 1, 'avg_within_class_degree': 3.16, 'avg_between_class_degree': 0.74, 'K': 1.5, 'seed': 4}}
2024-11-18 20:17:54 (INFO): model_params: {'label': 'GCN', 'model': 'GCN', 'normalization': 'row_normalization', 'depth': 1, 'regularizer': 0.01, 'pred_method': 'svm', 'activation': 'linear', 'solver': 'qplayer', 'alpha_tol': 0.0001, 'bias': False}
2024-11-18 20:17:54 (INFO): certification_params: {'attack': 'apgd', 'n_adversarial': 24, 'perturbation_model': 'linf', 'delta': 0.5, 'max_iter': 100, 'eta': 2, 'n_restarts': 0, 'delta_absolute': False, 'normalize_grad': True, 'attack_nodes': 'test', 'gradient_method': 'exact'}
2024-11-18 20:17:54 (INFO): verbosity_params: {'debug_lvl': 'info'}
2024-11-18 

CSBM mu:
[0.28347334 0.28347334 0.28347334 0.28347334 0.28347334 0.28347334
 0.28347334]


2024-11-18 20:17:54 (INFO): k 22, W: 22, y_pred_worst: -0.17605767697381391, eta: 0.2835
2024-11-18 20:17:55 (INFO): k 41, W: 41, y_pred_worst: -0.17605767697381391, eta: 0.14175
2024-11-18 20:17:55 (INFO): k 58, W: 58, y_pred_worst: -0.17605767697381391, eta: 0.070875
2024-11-18 20:17:55 (INFO): k 70, W: 70, y_pred_worst: -0.17605767697381391, eta: 0.0354375
2024-11-18 20:17:55 (INFO): k 80, W: 80, y_pred_worst: -0.17605767697381391, eta: 0.01771875
2024-11-18 20:17:55 (INFO): k 87, W: 87, y_pred_worst: -0.17605767697381391, eta: 0.008859375
2024-11-18 20:17:55 (INFO): k 93, W: 93, y_pred_worst: -0.17605767697381391, eta: 0.0044296875
2024-11-18 20:17:55 (INFO): W: [0, 22, 41, 58, 70, 80, 87, 93, 99]
2024-11-18 20:17:55 (INFO): k 22, W: 22, y_pred_worst: -0.0557625452517721, eta: 0.2835
2024-11-18 20:17:56 (INFO): k 41, W: 41, y_pred_worst: -0.0557625452517721, eta: 0.14175
2024-11-18 20:17:56 (INFO): k 58, W: 58, y_pred_worst: -0.0557625452517721, eta: 0.070875
2024-11-18 20:17:56 (I

KeyboardInterrupt: 

In [4]:
%reload_ext autoreload
#model_params["cache_size"] = 10000
seed = 4
data_params["specification"]["seed"] = seed
other_params["device"] = "cpu"
other_params["debug"] = False
attack_params["n_adversarial"] = 24
attack_params["delta"] = 0.5
attack_params["max_iter"] = 100
attack_params["eta"] = 2
attack_params["n_restarts"] = 0
attack_params["attack"] = "apgd"
attack_params["delta_absolute"] = False
attack_params["normalize_grad"] = True
attack_params["perturbation_model"] = "linf"
attack_params["attack_nodes"] = "test"
attack_params["gradient_method"] = "exact"
verbosity_params["debug_lvl"] = "info"
model_params["regularizer"] = 0.01
model_params["solver"] = "qplayer"
model_params["alpha_tol"] = 1e-4
model_params["bias"] = False
data_params["learning_setting"] = "transductive"
other_params["max_logging_iters"] = 0
other_params["store_attack_curve"] = False
run(data_params, model_params, attack_params, verbosity_params, other_params, seed)

2024-11-18 20:08:09 (INFO): Starting experiment exp_ntk_attack_backdoor with configuration:
2024-11-18 20:08:09 (INFO): data_params: {'dataset': 'csbm', 'learning_setting': 'transductive', 'specification': {'classes': 2, 'n_trn_labeled': 40, 'n_trn_unlabeled': 0, 'n_val': 40, 'n_test': 120, 'sigma': 1, 'avg_within_class_degree': 3.16, 'avg_between_class_degree': 0.74, 'K': 1.5, 'seed': 4}}
2024-11-18 20:08:09 (INFO): model_params: {'label': 'GCN', 'model': 'GCN', 'normalization': 'row_normalization', 'depth': 1, 'regularizer': 0.01, 'pred_method': 'svm', 'activation': 'linear', 'solver': 'qplayer', 'alpha_tol': 0.0001, 'bias': False}
2024-11-18 20:08:09 (INFO): certification_params: {'attack': 'apgd', 'n_adversarial': 24, 'perturbation_model': 'linf', 'delta': 0.5, 'max_iter': 100, 'eta': 2, 'n_restarts': 0, 'delta_absolute': False, 'normalize_grad': True, 'attack_nodes': 'test', 'gradient_method': 'exact'}
2024-11-18 20:08:09 (INFO): verbosity_params: {'debug_lvl': 'info'}
2024-11-18 

2024-11-18 20:08:09 (INFO): Delta: 0.2835
2024-11-18 20:08:09 (INFO): W: [0, 22, 41, 58, 70, 80, 87, 93, 99]


CSBM mu:
[0.28347334 0.28347334 0.28347334 0.28347334 0.28347334 0.28347334
 0.28347334]


2024-11-18 20:08:10 (INFO): k 22, W: 22, y_pred_worst: -0.17605767697381391, eta: 0.2835
2024-11-18 20:08:10 (INFO): k 41, W: 41, y_pred_worst: -0.17605767697381391, eta: 0.14175
2024-11-18 20:08:10 (INFO): k 58, W: 58, y_pred_worst: -0.17605767697381391, eta: 0.070875
2024-11-18 20:08:10 (INFO): k 70, W: 70, y_pred_worst: -0.17605767697381391, eta: 0.0354375
2024-11-18 20:08:10 (INFO): k 80, W: 80, y_pred_worst: -0.17605767697381391, eta: 0.01771875
2024-11-18 20:08:10 (INFO): k 87, W: 87, y_pred_worst: -0.17605767697381391, eta: 0.008859375
2024-11-18 20:08:10 (INFO): k 93, W: 93, y_pred_worst: -0.17605767697381391, eta: 0.0044296875
2024-11-18 20:08:10 (INFO): W: [0, 22, 41, 58, 70, 80, 87, 93, 99]
2024-11-18 20:08:11 (INFO): k 22, W: 22, y_pred_worst: -0.0557625452517721, eta: 0.2835
2024-11-18 20:08:11 (INFO): k 41, W: 41, y_pred_worst: -0.0557625452517721, eta: 0.14175
2024-11-18 20:08:11 (INFO): k 58, W: 58, y_pred_worst: -0.0557625452517721, eta: 0.070875
2024-11-18 20:08:11 (I

KeyboardInterrupt: 

In [20]:
%reload_ext autoreload
#model_params["cache_size"] = 10000
seed = 4
data_params["specification"]["seed"] = seed
other_params["device"] = "cpu"
other_params["debug"] = False
attack_params["n_adversarial"] = 24
attack_params["delta"] = 0.5
attack_params["max_iter"] = 100
attack_params["eta"] = 2
attack_params["n_restarts"] = 0
attack_params["attack"] = "apgd"
attack_params["delta_absolute"] = False
attack_params["normalize_grad"] = True
attack_params["perturbation_model"] = "linf"
attack_params["attack_nodes"] = "test"
verbosity_params["debug_lvl"] = "info"
model_params["regularizer"] = 0.01
model_params["solver"] = "qplayer"
model_params["alpha_tol"] = 1e-4
model_params["bias"] = False
data_params["learning_setting"] = "transductive"
other_params["max_logging_iters"] = 0
other_params["store_attack_curve"] = False
run_2(data_params, model_params, attack_params, verbosity_params, other_params, seed)

2024-11-17 16:25:26 (INFO): Starting experiment exp_ntk_attack with configuration:
2024-11-17 16:25:26 (INFO): data_params: {'dataset': 'csbm', 'learning_setting': 'transductive', 'specification': {'classes': 2, 'n_trn_labeled': 40, 'n_trn_unlabeled': 0, 'n_val': 40, 'n_test': 120, 'sigma': 1, 'avg_within_class_degree': 3.16, 'avg_between_class_degree': 0.74, 'K': 1.5, 'seed': 4}}
2024-11-17 16:25:26 (INFO): model_params: {'label': 'GCN', 'model': 'GCN', 'normalization': 'row_normalization', 'depth': 1, 'regularizer': 0.01, 'pred_method': 'svm', 'activation': 'linear', 'solver': 'qplayer', 'alpha_tol': 0.0001, 'bias': False}
2024-11-17 16:25:26 (INFO): certification_params: {'attack': 'apgd', 'n_adversarial': 24, 'perturbation_model': 'linf', 'delta': 0.5, 'max_iter': 100, 'eta': 2, 'n_restarts': 0, 'delta_absolute': False, 'normalize_grad': True, 'attack_nodes': 'test'}
2024-11-17 16:25:26 (INFO): verbosity_params: {'debug_lvl': 'info'}
2024-11-17 16:25:26 (INFO): other_params: {'devi

CSBM mu:
[0.28347334 0.28347334 0.28347334 0.28347334 0.28347334 0.28347334
 0.28347334]
 normalize grad: True
W: [0, 22, 41, 58, 70, 80, 87, 93, 99]


2024-11-17 16:25:27 (INFO): k 22, W: 22, y_pred_worst: -0.17605767697381391, eta: 0.2835
2024-11-17 16:25:27 (INFO): k 41, W: 41, y_pred_worst: -0.17605767697381391, eta: 0.14175
2024-11-17 16:25:27 (INFO): k 58, W: 58, y_pred_worst: -0.17605767697381391, eta: 0.070875
2024-11-17 16:25:27 (INFO): k 70, W: 70, y_pred_worst: -0.17605767697381391, eta: 0.0354375
2024-11-17 16:25:27 (INFO): k 80, W: 80, y_pred_worst: -0.17605767697381391, eta: 0.01771875
2024-11-17 16:25:27 (INFO): k 87, W: 87, y_pred_worst: -0.17605767697381391, eta: 0.008859375
2024-11-17 16:25:28 (INFO): k 93, W: 93, y_pred_worst: -0.17605767697381391, eta: 0.0044296875
2024-11-17 16:25:28 (INFO): y_pert: -0.17605768; y_clean: -0.33096602; Pert: False; Correct Clean: True; Total Pert: 0 Total Clean: 1.0; Total: 1
2024-11-17 16:25:29 (INFO): y_pert: -0.34970560; y_clean: -0.40280318; Pert: False; Correct Clean: True; Total Pert: 0 Total Clean: 2.0; Total: 2
2024-11-17 16:25:30 (INFO): y_pert: 0.11706122; y_clean: 0.23098

KeyboardInterrupt: 

In [24]:
%reload_ext autoreload
#model_params["cache_size"] = 10000
seed = 4
data_params["specification"]["seed"] = seed
other_params["device"] = "cpu"
other_params["debug"] = False
attack_params["n_adversarial"] = 16
attack_params["delta"] = 0.5
attack_params["max_iter"] = 100
attack_params["eta"] = 2
attack_params["n_restarts"] = 0
attack_params["attack"] = "apgd"
attack_params["delta_absolute"] = False
attack_params["normalize_grad"] = True
attack_params["perturbation_model"] = "linf"
attack_params["attack_nodes"] = "train_val"
verbosity_params["debug_lvl"] = "info"
model_params["regularizer"] = 0.01
model_params["solver"] = "qplayer"
model_params["alpha_tol"] = 1e-4
model_params["bias"] = False
data_params["learning_setting"] = "transductive"
other_params["max_logging_iters"] = 0
other_params["store_attack_curve"] = False
run(data_params, model_params, attack_params, verbosity_params, other_params, seed)

2024-11-17 16:38:27 (INFO): Starting experiment exp_ntk_attack_backdoor with configuration:
2024-11-17 16:38:27 (INFO): data_params: {'dataset': 'csbm', 'learning_setting': 'transductive', 'specification': {'classes': 2, 'n_trn_labeled': 40, 'n_trn_unlabeled': 0, 'n_val': 40, 'n_test': 120, 'sigma': 1, 'avg_within_class_degree': 3.16, 'avg_between_class_degree': 0.74, 'K': 1.5, 'seed': 4}}
2024-11-17 16:38:27 (INFO): model_params: {'label': 'GCN', 'model': 'GCN', 'normalization': 'row_normalization', 'depth': 1, 'regularizer': 0.01, 'pred_method': 'svm', 'activation': 'linear', 'solver': 'qplayer', 'alpha_tol': 0.0001, 'bias': False}
2024-11-17 16:38:27 (INFO): certification_params: {'attack': 'apgd', 'n_adversarial': 16, 'perturbation_model': 'linf', 'delta': 0.5, 'max_iter': 100, 'eta': 2, 'n_restarts': 0, 'delta_absolute': False, 'normalize_grad': True, 'attack_nodes': 'train_val'}
2024-11-17 16:38:27 (INFO): verbosity_params: {'debug_lvl': 'info'}
2024-11-17 16:38:27 (INFO): other_

CSBM mu:
[0.28347334 0.28347334 0.28347334 0.28347334 0.28347334 0.28347334
 0.28347334]


2024-11-17 16:38:27 (INFO): k 22, W: 22, y_pred_worst: -0.29007065237855567, eta: 0.2835
2024-11-17 16:38:28 (INFO): k 41, W: 41, y_pred_worst: -0.28935950360663637, eta: 0.14175
2024-11-17 16:38:28 (INFO): k 58, W: 58, y_pred_worst: -0.28898961908681603, eta: 0.14175
2024-11-17 16:38:28 (INFO): k 70, W: 70, y_pred_worst: -0.28898961908681603, eta: 0.070875
2024-11-17 16:38:28 (INFO): k 80, W: 80, y_pred_worst: -0.28842250588256263, eta: 0.070875
2024-11-17 16:38:28 (INFO): k 87, W: 87, y_pred_worst: -0.28842250588256263, eta: 0.0354375
2024-11-17 16:38:28 (INFO): k 93, W: 93, y_pred_worst: -0.2880080272529104, eta: 0.0354375
2024-11-17 16:38:28 (INFO): W: [0, 22, 41, 58, 70, 80, 87, 93, 99]
2024-11-17 16:38:28 (INFO): k 22, W: 22, y_pred_worst: -0.1714918555885944, eta: 0.2835
2024-11-17 16:38:29 (INFO): k 41, W: 41, y_pred_worst: -0.1714918555885944, eta: 0.14175
2024-11-17 16:38:29 (INFO): k 58, W: 58, y_pred_worst: -0.1714918555885944, eta: 0.070875
2024-11-17 16:38:29 (INFO): k 70

KeyboardInterrupt: 

In [27]:
data_params = dict(
    dataset = "cora_ml_cont_binary",
    learning_setting = "transductive", # or "transdructive"
    specification = dict(
        n_per_class = 5,
        fraction_test = 0.1,
        data_dir = "./data",
        make_undirected = True,
        binary_attr = False,
        balance_test = True,
    )
)

%reload_ext autoreload
#model_params["cache_size"] = 10000
seed = 4
data_params["specification"]["seed"] = seed
other_params["device"] = "cpu"
other_params["debug"] = False
attack_params["n_adversarial"] = 60
attack_params["delta"] = 0.1
attack_params["max_iter"] = 30
attack_params["eta"] = 2
attack_params["n_restarts"] = 0
attack_params["attack"] = "apgd"
attack_params["delta_absolute"] = True
attack_params["normalize_grad"] = True
attack_params["perturbation_model"] = "linf"
attack_params["attack_nodes"] = "test"
attack_params["n_attack"] = 100
verbosity_params["debug_lvl"] = "info"
model_params["regularizer"] = 0.75
model_params["solver"] = "qplayer"
model_params["alpha_tol"] = 1e-4
model_params["bias"] = False
data_params["learning_setting"] = "transductive"
other_params["max_logging_iters"] = 0
other_params["store_attack_curve"] = False
run(data_params, model_params, attack_params, verbosity_params, other_params, seed)

2024-05-16 20:57:42 (INFO): Starting experiment exp_ntk_attack with configuration:
2024-05-16 20:57:42 (INFO): data_params: {'dataset': 'cora_ml_cont_binary', 'learning_setting': 'transductive', 'specification': {'n_per_class': 5, 'fraction_test': 0.1, 'data_dir': './data', 'make_undirected': True, 'binary_attr': False, 'balance_test': True, 'seed': 4}}
2024-05-16 20:57:42 (INFO): model_params: {'label': 'GCN', 'model': 'GCN', 'normalization': 'row_normalization', 'depth': 1, 'regularizer': 0.75, 'pred_method': 'svm', 'activation': 'relu', 'solver': 'qplayer', 'alpha_tol': 0.0001, 'bias': False}
2024-05-16 20:57:42 (INFO): certification_params: {'attack': 'apgd', 'n_adversarial': 60, 'perturbation_model': 'linf', 'delta': 0.1, 'max_iter': 30, 'eta': 2, 'n_restarts': 0, 'delta_absolute': True, 'normalize_grad': True, 'attack_nodes': 'test', 'n_attack': 100}
2024-05-16 20:57:42 (INFO): verbosity_params: {'debug_lvl': 'info'}
2024-05-16 20:57:42 (INFO): other_params: {'device': 'cpu', 'dt

 normalize grad: True
W: [0, 7, 13, 18, 22, 24, 27, 28, 30]


2024-05-16 20:57:46 (INFO): k 7, W: 7, y_pred_worst: 0.03350209342833793, eta: 0.1
2024-05-16 20:57:47 (INFO): k 13, W: 13, y_pred_worst: 0.03951634771166246, eta: 0.1
2024-05-16 20:57:49 (INFO): k 18, W: 18, y_pred_worst: 0.03951634771166246, eta: 0.05
2024-05-16 20:57:50 (INFO): k 22, W: 22, y_pred_worst: 0.040476080859466745, eta: 0.05
2024-05-16 20:57:50 (INFO): k 24, W: 24, y_pred_worst: 0.04154515310179435, eta: 0.05
2024-05-16 20:57:51 (INFO): k 27, W: 27, y_pred_worst: 0.04154515310179435, eta: 0.025
2024-05-16 20:57:51 (INFO): k 28, W: 28, y_pred_worst: 0.04154515310179435, eta: 0.025
2024-05-16 20:57:52 (INFO): y_pert: 0.04154515; y_clean: -0.89096431; Pert: True; Correct Clean: False; Total Pert: 1 Total Clean: 0.0; Total: 1
2024-05-16 20:58:00 (INFO): y_pert: -0.56329113; y_clean: -0.98153260; Pert: False; Correct Clean: True; Total Pert: 1 Total Clean: 1.0; Total: 2


KeyboardInterrupt: 